### ISSUE TITLE
Initial Two Week: Progress Check 1.

### ISSUE THREAD

**Issue by dbasargin** [dbasargin/TicketSystem#1]
**Derek and Dennis**
   1. Plan database for a Ticket management System.
   2. Get both dennis and derek signed into github and access to ticketsystem Repo .
   [https://github.com/dbasargin/TicketSystem] -repo link
   3. Make sure we both have access to github Solution on visual studio.
   4. Plan next Progress.
   5. Plan different form for application.

**Derek**
   6. Create script with all main tables to start.
   7. Decide whether to add to solution or wait till we add more functionality.

**Dennis**
   8. Set up github repo.
   9. Create initial project solution. tie to github.

**Comment by Joe-Ortiz** [comment]
This will work for the first progress check. You can split up your tasks into multiple Issues here on GitHub. That way you can close each Issue as your are going along instead of trying to update a single issue and keep track of everything.
