### ISSUE TITLE
Create Form and Design "Create event"

### ISSUE THREAD

**Issue by dbasargin** [dbasargin/TicketSystem#15]
Create Form and Design "Create event".
Create text boxes and buttons that tie all data entered to update database.

**Comment by dbasargin** [comment]
This is something I Think I will postpone until. We create a menu with parent form.

**Comment by skyhigh697** [comment]
I have been working on it but have gotten stuck up on the form actually adding to the Database

**Comment by skyhigh697** [comment]
Got this working will finish up design today
