### ISSUE TITLE
Create "Display Event Details"

### ISSUE THREAD

**Issue by dbasargin** [dbasargin/TicketSystem#16]
Create "Display Event Details"

after selecting item on homepage
-pull data from the database and display
all event data nicely(figure out how and where?).

**Comment by dbasargin** [comment]
HEy Derek, Just wanted to show you I updated the Main form to be able to pass selected event to your EventDetails Form. Also I had to update the FrmEventDetails Constructor to accept the event as a parameter. 
![eventdetails](https://cloud.githubusercontent.com/assets/22454934/22584053/31defbcc-e9a5-11e6-8f70-291be67355a1.PNG)
![frmdetails](https://cloud.githubusercontent.com/assets/22454934/22584047/26b737d2-e9a5-11e6-9ba5-c06cd02e25d8.PNG)

**Comment by skyhigh697** [comment]
Got the initial stuff up and running.  we can tweak it some more as we continue the project
