### ISSUE TITLE
Figure out entities at home. 

### ISSUE THREAD

**Issue by dbasargin** [dbasargin/TicketSystem#18]
Ask joe how after creating entites with database at school then updating at home without the database.
Do we have to run the db script at home? if so how will the connection string change, will we have to have different connection strings?

or should entity create the database for  us now?

**Comment by Joe-Ortiz** [comment]
@dbasargin you should be able to run the database script at home and then your project will work there too. Unfortunately, I do not believe that the database first approach allows Entity Framework to create the database for you.

Make sure to check the App.Config file for the connection string. The data source might need to be changed from localhost to localhost\sqlexpress or another instance name.

**Comment by dbasargin** [comment]
The fix for this is to make sure after running the script on your home computer, in the app config file in solution at home might be different. for example(localhost/sqlexpress) instead of localhost in order to make this work at home you will need to change that piece of code in connection string while working from home.

ignore appconfig. file from home when committing, that way it will work at school too.
